### ISSUE TITLE
Not view theme in EasyAdmin 4 and Symfony 6

### ISSUE THREAD

**Issue by samspade0069** [agence-adeliom/easy-media-bundle#10]
I can't show theme of media manager and i don't know what doing wrong. I have followed the instrucctions up to section Manage medias in your Easyadmin dashboard. Attach screenshot of show media index.

![easyMediaScreen](https://user-images.githubusercontent.com/11518975/194372220-311bf757-68f4-4e2f-ac23-9b47a08063a2.JPG)

Thanks for your time.

**Comment by stipic** [comment]
run `bin/console assets:install`
