### ISSUE TITLE
Error in fileIsType method

### ISSUE THREAD

**Issue by j0r1s** [agence-adeliom/easy-media-bundle#15]
In `src/Service/EasyMediaHelper`, there is this condition inside `fileIsType` method.

```php
if ((($type && str_contains((string) $type, 'image')) || in_array($type, $mimes['image'] ?? [])) && 'image' !== $compare) {
    return true;
}
```

This will return true if we compare, for example `image/jpeg` with `video`. 
I think this is not expected and I'd be glad to open a PR in order to fix this but I don't really understand what this condition should be.

Maybe you can help me here @arnaud-ritti ?

**Comment by arnaud-ritti** [comment]
I fixed it in v2.0.17
