### ISSUE TITLE
EasyMediaManager error after updating

### ISSUE THREAD

**Issue by j0r1s** [agence-adeliom/easy-media-bundle#21]
Hello ! Thans a lot for fixing some issues in the latest updates.

I am now getting this error after updating to latest version (2.0.31) : 
`Adeliom\EasyMediaBundle\Service\EasyMediaManager::__construct(): Argument #1 ($filesystem) must be of type League\Flysystem\FilesystemOperator, League\Flysystem\Local\LocalFilesystemAdapter given`

**Comment by NOaMTL** [comment]
Same for me

**Comment by JeroenMoonen** [comment]
Since the last update, FlySystem dependency package has been updated. Update your config:

```
easy_media:
  storage_name: 'default.storage'
```

**Comment by arnaud-ritti** [comment]
Sorry, for this i have change the documentions according this issue

**Comment by j0r1s** [comment]
Thanks for correcting !

I dont know if it's relevant, but I had to add `base_url: "/media/download"` to my config in order to make my medias resolve after updating the bundle.
