### ISSUE TITLE
When loading EasyFields/form/choice_mask_widget.html.twig the panels are not displayed anymore

### ISSUE THREAD

**Issue by jdadeliom** [agence-adeliom/easy-media-bundle#24]
```php
public function configureCrud(): Crud
    {
        return Crud::new()
            ->addFormTheme('@EasyCommon/crud/custom_panel.html.twig')
            ->addFormTheme('@EasyFields/form/choice_mask_widget.html.twig')
        ;
    }
```

when using `custom_panel` with `choice_mask_widget`, the panels don't work anymore

**Comment by jdadeliom** [comment]
When not using `choice_mask_widget`

![Capture d’écran 2023-08-03 à 14 06 53](https://github.com/agence-adeliom/easy-media-bundle/assets/97044531/e42f10a2-84be-4585-85ca-63e2d16d7f3c)

When using it

![Capture d’écran 2023-08-03 à 14 07 19](https://github.com/agence-adeliom/easy-media-bundle/assets/97044531/510005da-83f6-4b77-9336-19b753a1cc47)

**Comment by arnaud-ritti** [comment]
You have to switch them because choice_mask_widget need to change fields row attrs

```php
public function configureCrud(): Crud
{
    return Crud::new()
        ->addFormTheme('@EasyCommon/crud/custom_panel.html.twig')
        ->addFormTheme('@EasyFields/form/choice_mask_widget.html.twig')
    ;
}
```

this is working

**Comment by arnaud-ritti** [comment]
But custom panel will be removed because it is not following EasyAdmin UI, feel free to add a custom css class and add your own css styles if needed
