### ISSUE TITLE
Media Manager not working when folder has been deleted

### ISSUE THREAD

**Issue by jdadeliom** [agence-adeliom/easy-media-bundle#4]
When I go to a folder, his folderId is stored inside localStorage. It is used then to access the same folder when opening the media library.
But if I delete the folder, the folderId may still be inside the localStorage.
The bundle should check if the doesn't exist then it should load the root of the media library, cause as of today it prevent to do anything.

![media-library-error](https://user-images.githubusercontent.com/97044531/154247326-c522c9b5-e06c-4e2a-b363-b5a52278a6e1.png)

**Comment by arnaud-ritti** [comment]
This issue is not handled.

New behavior : when the folder not exist, it goes to the parents while folder does not exist.
