### ISSUE TITLE
It is illegal to put an inverse side one-to-many or many-to-many association 

### ISSUE THREAD

**Issue by NOaMTL** [agence-adeliom/easy-media-bundle#9]
Hello,

I get this error : 

> It is illegal to put an inverse side one-to-many or many-to-many association on mapped superclass 'Adeliom\EasyMediaBundle\Entity\Folder#children'

i am using Symfony 6.1 and Easyadmin 4.3.5 and easy-media-bundle 2.0.9

If you have any idea...
Thank you

**Comment by arnaud-ritti** [comment]
Hi, 

Did you have created the entity Folder and Media has explained here https://github.com/agence-adeliom/easy-media-bundle#without-symfony-flex ?
